/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int APAR = 9;
  /** RegularExpression Id. */
  int FPAR = 10;
  /** RegularExpression Id. */
  int NEWVAR = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int TINT = 14;
  /** RegularExpression Id. */
  int TBOOL = 15;
  /** RegularExpression Id. */
  int CATRIB = 16;
  /** RegularExpression Id. */
  int CIF = 17;
  /** RegularExpression Id. */
  int CTHEN = 18;
  /** RegularExpression Id. */
  int CWHILE = 19;
  /** RegularExpression Id. */
  int CREP = 20;
  /** RegularExpression Id. */
  int CUNT = 21;
  /** RegularExpression Id. */
  int CRET = 22;
  /** RegularExpression Id. */
  int CPRINT = 23;
  /** RegularExpression Id. */
  int CREADINT = 24;
  /** RegularExpression Id. */
  int BTRUE = 25;
  /** RegularExpression Id. */
  int BFALSE = 26;
  /** RegularExpression Id. */
  int FUNC = 27;
  /** RegularExpression Id. */
  int OP = 28;
  /** RegularExpression Id. */
  int ID = 29;
  /** RegularExpression Id. */
  int NUM = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"(\"",
    "\")\"",
    "\"newVar\"",
    "\";\"",
    "\",\"",
    "\"integer\"",
    "\"bool\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.output\"",
    "\"System.readint\"",
    "\"true\"",
    "\"false\"",
    "\"func\"",
    "<OP>",
    "<ID>",
    "<NUM>",
  };

}
